### ISSUE TITLE
Windows lib named "rav1e.dll.lib"

### ISSUE THREAD

**Issue by carterbox** [conda-forge/rav1e-feedstock#2]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

For rav1e-0.6.6-h980a851_0, the Windows lib is named "rav1e.dll.lib". This is a very unusual name; I would expect it to be "rav1e.lib".

### Installed packages

```shell
rav1e-0.6.6-h980a851_0
```

### Environment info

```shell
None
```

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
can i justrename the file.

**Comment by hmaarrfk** [comment]
i feel like some packages consider the `library.lib` to be static.

thus the name `library.dll.lib` specifies it is dynamic.

**Comment by hmaarrfk** [comment]
It seems to be hardcoded in cargo-c 

https://github.com/lu-zero/cargo-c/blob/master/src/build.rs#L262

**Comment by carterbox** [comment]
The problem I'm actually trying to solve is that libavif wasn't able to find this library. I suspect it's related to this weird naming, but I didn't actually test it. We may need to make changes upstream.

**Comment by hmaarrfk** [comment]
i think that many times on windows, people like to statically link, or they don't try very hard to create shared libraries.

I tried very hard to get rid of the static libraries, if any, and only build the shared ones.

so you might need a small patch that tries to find the `rav1e` dynamic library instead of the static one.

**Comment by carterbox** [comment]
For more background, the reason, I suspect this library is named incorrectly is because the pc file contains:

```
prefix=D:/bld/rav1e_1687765718803/_h_env/Library
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: rav1e
Description: The fastest and safest AV1 encoder
Version: 0.6.6
Libs: -L${libdir} -lrav1e
Cflags: -I${includedir}/rav1e
Libs.private: 
```
Which doesn't mention rav1e.dll.lib

**Comment by carterbox** [comment]
OR maybe the problem is just that the prefix in the PC file is wrong. It should be `%PREFIX%/Library`?
